### ISSUE TITLE
ClassNotFoundException: edu.uoc.som.wapiml.ui.handlers.ConvertToClassDiagramYaml cannot be found by edu.uoc.som.wapiml.ui_1.2.0.qualifier

### ISSUE THREAD

**Issue by casmir11767** [opendata-for-all/wapiml#40]
[Logfile.txt](https://github.com/opendata-for-all/wapiml/files/3829340/Logfile.txt)
[ReferenceData.yaml.txt](https://github.com/opendata-for-all/wapiml/files/3829292/ReferenceData.yaml.txt)

In the log file I find this message

The proxied handler for ‘edu.uoc.som.wapiml.ui.handlers.ConvertToClassDiagramYaml’ could not be loaded

Caused by: java.lang.ClassNotFoundException: edu.uoc.som.wapiml.ui.handlers.ConvertToClassDiagramYaml cannot be found by edu.uoc.som.wapiml.ui_1.2.0.qualifier

Do you knwow what’s the problem?

a) I create a Project
b) I open my YAML
c) I Right-click on the YAML file and select WAPIml/Generate a class diagram to start.

Nothing is happening
This will not initiate a wizard to guide the generation process.

My installation

1) Eclipse Version: 2019-09 R (4.13.0)
2) Eclipse Modeling Project – Papyrus UML Modeller 4.5.0.201909110825
3) Eclipse Modeling Project – UML2 5.5.0.v20181203-1331

**Comment by hamzaed** [comment]
Hi, 

It seems that WAPIml was not properly installed in your Eclipse. You should install it using the update site as mentioned in the [Readme](https://github.com/opendata-for-all/wapiml/blob/master/README.md#installation).

Your installation includes the ".qualifier" extension. Did you drag and drop the plugins into your eclipse installation folder? This will not work since WAPIml has many dependencies that are resolved when installing it using the update site. If for some reasons you want to import the source code and build it yourself, you need to rely on Maven for this.

I suggest that you remove WAPIml from you Eclipse installation and start over using the update site.

Hamza

**Comment by casmir11767** [comment]
Hi,
I uninstalled and reinstalled.

Thank you,
